### ISSUE TITLE
Bug with whistle contour (ROCCA)

### ISSUE THREAD

**Issue by elisecab** [PAMGuard/PAMGuard#100]
Hello,
It's impossible for me to use ROCCA classifier with some files. The whistle contour doesn't appear after selecting the beginning and the end of the whistle or with "pick points". With other files, it works very good and some it doesn't do the exact whistle and go on places where there is no whistle even with a thresold of 10.
I see that the red vertical line (filter) is not on all the lenght of the files that doesn't work, and just at the end or doesnt' appear at all.
How can I resolve the problem and pick the whistles contour from my .wav files ? Thank you.

**Comment by macster110** [comment]
Apologies for the very reply. Please contact the ROCCA classifier folks about this- ROCCA is maintained outside of PAMGuard's core code. I'll close this issue for now.
