### ISSUE TITLE
Reference paper of bearing localization algorithm

### ISSUE THREAD

**Issue by scofir** [PAMGuard/PAMGuard#115]
Could you please provide some reference papers on algorithms used in the bearingLocaliser and Group3DLocaliser modules? I am very interested in them, thank you

**Comment by scofir** [comment]
I would be grateful if I could get a reference for group3d's positioning algorithm

**Comment by macster110** [comment]
Apologies this has taken so long. There are no references per say but these two papers describe the algorithms:

https://pubs.aip.org/asa/jasa/article/141/2/1120/989130/Passive-acoustic-methods-for-fine-scale-tracking

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0229058
