### ISSUE TITLE
Large datasets cause PAMGuard freeze at startup

### ISSUE THREAD

**Issue by macster110** [PAMGuard/PAMGuard#156]
When processing large datasets, PAMGuard can freeze for minutes or even tens of minutes. 

This is because ReprocessManager.checkIOFilesStatus() iterates through all files and extracts the time. For a sud files and some other types of audio file, this means opening the header of the file. For a few dozen files then the freeze is not perceptible, but for very large datasets e.g. a single deployment of an ST640 this results in a thread. 

Action: Reprocess manager needs to be put on a seperate thread with an update progress bar to show the user PAMGuard is working

**Comment by douggillespie** [comment]
This was fixed in a commit yesterday. Will be in next release. It still takes time to run the checks, but does at least show a progress bar whild catalogueing the files.
