### ISSUE TITLE
Clicks are not selectable in viewer mode above a load size of 00:30:00

### ISSUE THREAD

**Issue by macster110** [PAMGuard/PAMGuard#158]
When the loaded data in the click detector display is above 30 minutes, clicks can no longer be selected on the click display. Selecting a click selects another clicks randomly in another part of the data. This has been tested on multiple viewer databases with different samples rates and processing dates.

**Comment by douggillespie** [comment]
Should be fixed. Issue seems to have been that the display was searching clicks very far from the displayed area ,which caused fixed point overflows.

**Comment by macster110** [comment]
Fixed as of release version 2.02.14
