### ISSUE TITLE
Click Selection in Viewer 2.02.13

### ISSUE THREAD

**Issue by sgkeith** [PAMGuard/PAMGuard#173]
Hi,

Clicks become unselectable in PAMGuard Viewer when the click display is any smaller than 1 min for half a 1080p screen (or 2 min for a 2160p screen). The problem does not exist in 2.02.10.

Selectable:
![PGViewer_bug - Selectable 1080p](https://github.com/user-attachments/assets/cf7d9bea-b880-4547-a2f5-a8cd306a1b2c)

Not Selectable:
![PGViewer_bug - Not Selectable 1080p](https://github.com/user-attachments/assets/9cee0fa2-b3e1-4839-bb57-1edb1cf8ee38)

**Comment by macster110** [comment]
Thanks for creating the issue. This was due to an integer overflow error on 4K screens and has been fixed as of version 2.02.14. See [issue](https://github.com/PAMGuard/PAMGuard/issues/158) here.
