### ISSUE TITLE
TD/Fx Display Freezes with Clicks

### ISSUE THREAD

**Issue by lizferguson5** [PAMGuard/PAMGuard#27]
Hi All, 

This is in reference to a long time issue I've had with the TD/Fx display freezes when I have clicks in one of the panels and am logging clicks to a DGL event (as I can't do that in the click detector panel). The problem was a little better I thought when I used the amplitude - stem button, but still problematic. The freezing happens after 30 minutes or after 2 minutes and seems to do it less if I have less data loaded, although if I have more than an hour of data loaded then it freezes more often (for all other panels, I have a day of data loaded and no freezing). I've tried de-selecting some clicks, and always de-select the unclassified. It makes it pretty time consuming to assign clicks to an event and 

I have a Win 10, 32 GB RAM (but PG only has access to 16 GB, and I've tried more, less, with no difference), I have had this problem on different computers (others working through data and my laptop) and with all datasets and all versions of PAMGuard since about 2019 when I started it. Jamie and I have tried trouble shooting  a lot but he can't replicate the problem. I am overlaying audio if that helps (to confirm species, etc.) but not in the TD/Fx display and the problem occurs without overlay as well. 

Here's a video displaying the problem (one of my tests for Mike a while back, same freezing happens though - look at min 6): 
https://screencast-o-matic.com/watch/crit14ViGB1

Here's a set of test files that have had the issue occur. 
https://drive.google.com/drive/folders/1kvDAGPphWr-dL_IQXwdyya0sbvWtXfwL?usp=sharing

Appreciate any help!

**Comment by macster110** [comment]
Hi @lizferguson5  - I had another go at this and I just could not replicate the error. I am, however, using a Mac so perhaps this is a Windows specific issue. I will try and find a PC and see what I can do.

**Comment by lizferguson5** [comment]
Hi there just thought I would check in on this one!

**Comment by macster110** [comment]
It's been hard to replicate this issue and it seems to be fundamental to JavaFX - it may well have fixed itself in new releases of JavaFX. If not, then please post a new issue.
