### ISSUE TITLE
Bug in SoundSpotClassifier, GenericDLClassifier, and KetosClassifier

### ISSUE THREAD

**Issue by Hauechri** [PAMGuard/PAMGuard#61]
private function and an overwritten function with the same name and parameters.

@Override
public void newResult(GenericPrediction modelResult, GroupedRawData groupedRawData) {
modelResult.setClassNameID(getClassNameIDs(genericModelParams));
modelResult.setBinaryClassification(isBinaryResult(modelResult, genericModelParams));
newResult(modelResult, groupedRawData);
}

The problem is that both functions are ambiguous, which means that in my case, newResult was calling itself endlessly. To fix this, the private function must be renamed.

**Comment by macster110** [comment]
Fixed
